### ISSUE TITLE
JCommander#parseValues throws NullPointerException (since 1.71)

### ISSUE THREAD

**Issue by ldaume** [cbeust/jcommander#367]
During the changes in [commit 4435722a0b45be660b1b58834d4f5326fc78c9ad](https://github.com/cbeust/jcommander/commit/4435722a0b45be660b1b58834d4f5326fc78c9ad#diff-b658a3c4420af2b046c522979a5973be) new defect has crept in which raises a NullPointerException.

```java
Exception in thread "main" java.lang.NullPointerException
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:718)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parseWithoutValidation(JCommander.java:330)
```

The Boolean in line 717 `Boolean value = (Boolean) pd.getParameterized().get(pd.getObject());` can be null if no default value is present for a Boolean parameter like:
```java
@Parameter(names = {"--flag"}, description = "Just a simple flag")
private Boolean simpleFlag;
```

This behaviour is not obvious because strings can be null. And a nullable parameter is important if one just wants to override a configured value with those of the command line if they are present.

**Comment by jeremysolarz** [comment]
Seems right. 

```
@Test
    public void booleanNoDefault() {
        class Args {
            @Parameter(names = {"--f"}, description = "Just a simple flag")
            private Boolean f;
        }
        try {
            Args args = new Args();
            JCommander.newBuilder()
                    .addObject(args)
                    .build().parse("--f");
            Assert.assertEquals(args.f, null);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
```
Is failing. Also TypeHierarchyTest#testTypeHierarchy is failing.

@cbeust strange that this wasn't picked up by the automated testing, I see the [Travis CI](https://travis-ci.org/cbeust/jcommander/builds/235226147?utm_source=github_status&utm_medium=notification) passes ... strange 😕

**Comment by jeremysolarz** [comment]
When running the latest `master` locally with `gradle test` the following is the output:

```
Gradle suite > Gradle test > com.beust.jcommander.TypeHierarchyTest.testTypeHierarchy FAILED
    java.lang.NullPointerException at TypeHierarchyTest.java:102

227 tests completed, 1 failed
:test FAILED
```

**Comment by glhez** [comment]
The fix is wrong to me: with the given example and to my understanding of jcommander :

- version 1.69: `simpleFlag` was set to **`true`** if `--flag` was passed.
- version 1.71: `simpleFlag` was inverted if related attribute was not `null` (otherwise it would raise a NPE).
- version 1.72: `simpleFlag` was inverted unless if `null` in which case it was not set.

Some legit case of using `null`: check if the flag was never set (eg: true = enable, false = disable, null = default).

I fixed this behavior in PR #373 : the change also fix another part of the code where the null check was not done in another part.

**Comment by bisoldi** [comment]
I suspect my issue is related.  Using 1.72, I tracked the NPE to the same line JCommander.java (line 718) though in my case it was while creating a help parameter without giving the Boolean variable a default value.  As soon as I the Boolean to false at declaration, it worked.

```
Exception in thread "main" java.lang.NullPointerException
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:718)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
```
Here is my code snippet:

```
import com.beust.jcommander.Parameter;

public class CmdLineArgs {
    
    @Parameter(names = {"--help", "-h"}, description = "Display help for this application", help = true)
    private Boolean help;
    
    @Parameter(names = {"--topic", "-t"}, description = "Sets a single topic (can be multiple words) for the processing of the articles")
    private String topic;

    public Boolean getHelp() {
        return help;
    }

    public void setHelp(Boolean help) {
        this.help = help;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }
}
```
```
public static void main(String[] args) throws IOException, ExportException {
    CmdLineArgs cmdLine = new CmdLineArgs();
    JCommander jcmd = JCommander.newBuilder()
            .addObject(cmdLine)
            .build();
        
    jcmd.parse(args);

    if (cmdLine.getHelp()) {
        System.out.println("help");
        System.exit(0);
    }
```

**Comment by cbeust** [comment]
This appears to work for me:

```
    @Test
    public void issue367() {
        class CmdLineArgs {

            @Parameter(names = {"--help", "-h"}, description = "Display help for this application", help = true)
            private Boolean help;

            @Parameter(names = {"--topic", "-t"}, description = "Sets a single topic (can be multiple words) for the processing of the articles")
            private String topic;

            public Boolean getHelp() {
                return help;
            }

            public void setHelp(Boolean help) {
                this.help = help;
            }

            public String getTopic() {
                return topic;
            }

            public void setTopic(String topic) {
                this.topic = topic;
            }
        }

        CmdLineArgs cmdLine = new CmdLineArgs();

        JCommander jcmd = JCommander.newBuilder()
                .addObject(cmdLine)
                .build();

        jcmd.parse(new String[] { "-h" });

        if (cmdLine.getHelp()) {
            System.out.println("help");
            System.exit(0);
        }
    }
```

Can you modify this test to show your error?

**Comment by bisoldi** [comment]
Unfortunately, it does not work for me.  Using 1.72, I still get a nullpointerexception, however as soon as I switched the dependency to 1.69, it worked fine.  Below is the test class I used.

```
package com.myapp.models;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import org.junit.Test;

public class CmdLineArgsTest {
    
    class CmdLineArgs {

        @Parameter(names = {"--help", "-h"}, description = "Display help for this application", help = true)
        private Boolean help;

        @Parameter(names = {"--topic", "-t"}, description = "Sets a single topic (can be multiple words) for the processing of the articles")
        private String topic;

        public Boolean getHelp() {
            return help;
        }

        public void setHelp(Boolean help) {
            this.help = help;
        }

        public String getTopic() {
            return topic;
        }

        public void setTopic(String topic) {
            this.topic = topic;
        }
    }

    @Test
    public void testCmdLineArgs() {

        CmdLineArgs cmdLine = new CmdLineArgs();

        JCommander jcmd = JCommander.newBuilder()
                .addObject(cmdLine)
                .build();

        jcmd.parse(new String[]{"-h"});

        if (cmdLine.getHelp()) {
            System.out.println("help");
            System.exit(0);
        }
    }

}
```
Here is the full stack trace:

```
java.lang.NullPointerException
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:718)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
	at com.myapp.models.CmdLineArgsTest.testCmdLineArgs(CmdLineArgsTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by glhez** [comment]
@cbeust The problem is still there using version from maven central. I don't know how to publish a new version to central and perhaps it is a task that fall on you being main maintainer :) (beside if I use `./kobaltw clean compîle publishToMavenLocal` on WIndows, it fails with `java.lang.IllegalArgumentException: Illegal character in opaque part at index 11: jar:file:E:\git\github\jcommander\.\kobaltBuild\` => you might need to use Path.toURI() or File.toURI() ...)
Nonetheless, my fix fix your problem @bisoldi .

**Comment by Hrushi20** [comment]
I am facing the same issue in version 1.81

![Screenshot (19)](https://user-images.githubusercontent.com/65367566/126912430-89b86757-4793-46fd-a278-6aac3950c8df.png)

I am able to print the entire todo using the --addTodo argument, but am get null pointer exception while printing the getParsedCommand
