### ISSUE TITLE
Accepting a single main parameter doesn't appear to be possible

### ISSUE THREAD

**Issue by trejkaz** [cbeust/jcommander#90]
We only support opening a single case at a time, so I figured I would just use this for accepting the location as the main parameter:

```
@Parameter(descriptionKey = "DesktopMainArguments.docLocation")
public File docLocation;
```

Attempting to parse then throws the following exception:

```
com.beust.jcommander.ParameterException: Main parameter field public java.io.File com.acme.main.MainArguments.docLocation needs to be of type List, not class java.io.File
```

I'm sure I could change it to a list, but then I would have to put in boilerplate to check that the user hasn't specified more than one.  Is there a proper way to do this directly?  Because I can't seem to find it in the examples or in the API.

I thought validation might be the way to do it, but I suspect I was wrong about that because the validator receives the original command-line string, not the final converted object.

**Comment by sbyron15** [comment]
This limitation is currently causing me a pretty big headache. Any interest is revisiting this? Is it a big change?

**Comment by cbeust** [comment]
What kind of headache? It should be just

```
if (main.size() != 1) throw IllegalArgumentException("Should have exactly one main parameter")
```

**Comment by sbyron15** [comment]
I'm trying to use JCommander along with [schema form](https://github.com/json-schema-form/angular-schema-form) to create dynamic forms for creating commands.

The problem being if I use `List<String>` in my POJO then schema form displays this as an array in the form, which is not what I want to show users.

**Comment by cbeust** [comment]
I don't follow, can you elaborate, maybe with some code?

The objection in this issue can be addressed with the one liner I supplied above, I'm not sure what else is needed.

**Comment by sbyron15** [comment]
You're line of code above doesn't address the root of the issue, which is that my command only supports one parameter. 

In my case, this is a deal breaker because I'm also serializing the command POJO to JSON for use with schema form. This is what I'm trying to do; lets say I have a command with a single argument and a flag:

`command file.txt --debug`

My Java class would look something like this:
```
public class Command {
    @JsonProperty("file")
    @Parameter(description = "File to process")
    String file;

    @JsonProperty("debug")
    @Prameter(names = {"-d", "--debug"})
    boolean debug;
}
```
Which needs to be serialized to:
```
{
    "file": "file.txt",
    "debug": true
}
```
Changing `file` to be of type `List<String>` is not an option, as it messes up the JSON.

**Comment by cbeust** [comment]
Ah, I see. I think serializing your arg straight to JSON is probably not the wisest approach but I understand the use case now.

**Comment by acostalima** [comment]
> Ah, I see. I think serializing your arg straight to JSON is probably not the wisest approach but I understand the use case now.
I agree with @cbeust here. We don't know exactly the full extent of your use cases, but it might be wise to rely on some interface to convert/serialize your JCommander commands to JSON.

**Comment by rtomsick** [comment]
@trejkaz has a valid point.

Intuitively, if I write:

```java
@Parameter(arity = 1)
public List<String> foo;
```
I would expect at most one entry in `foo`.  That doesn't happen now (in direct contradiction of the JavaDoc, FWIW.)

Even better would be allowing `@Parameter(arity = 1)` to apply to any type, not just `List`.

Yes, it is possible to work around this now, but DRY is a valid concern.  There's no good reason to make the caller write the same validation code every time for what is actually a pretty reasonable use case...

**Comment by walles** [comment]
I just wrote what @rtomsick has in the example above, and my `arity` had no effect.

So I had to start Googling for this problem and finally found my way here.

If `arity = 1` would have worked for my main parameter, that would have saved me time.

I find the current behavior of ignoring `arity` for the main parameter to be confusing.

I was also unable to find anything about this behavior in the `arity` documentation: <http://jcommander.org/#_arities_multiple_values_for_parameters>

Could you please handle `arity` for main parameters as well?

**Comment by rtomsick** [comment]
I guess that from a logical perspective the current behavior is arguably not incorrect; you are specifying a single list of Strings, which I suppose is fulfilled if you have 2 Strings in said list...


... but that's one hell of a reach, so yeah, it should be fixed. :smile:

**Comment by cbeust** [comment]
I'm ok with the idea of adding an arity to a main parameter like @rtomsick suggested:

    @Parameter(arity = 1)
    public List<String> foo;

but this will not fix OP's problem, who wants something more along the lines of:

    @Parameter
    public String foo;

This I'm still not completely sold on.

**Comment by rtomsick** [comment]
> This I'm still not completely sold on.

Why not?

Looking at it from an API design perspective, it passes pretty much all of the tests I can think of:

1) Simplicity - yep, it's about as simple as anything else with JCommander.

2) Compatibility - well it won't break the existing usage of `@Parameter` according to documentation, and since currently single-argument cases are handled with `List<?>`, non-collection types don't present any issue that I can see.

3) Expression of intent - OK, arguably it wouldn't be as clear as it could be.  *However* since the status quo is even less clear (`@Parameter` doesn't need a name when on a `List`, but does elsewhere?!) it's not any worse.  If you're really going for API consistency, then I'd propose something like **Ex. 1**  But even as written it's not too bad.

4) Allows future extension - sure.  If the no-property form of `Parameter` needed to be repurposed for something else, one migration path would be to deprecate it within a minor release, add a property as a temporary way to indicate that it should behave however the no-property form *will* behave, then in the next major do the switchover with the old (single argument) behavior moving to a new annotation (`@SingleParameter` or whatever.)  Or you could just implement said annotation to start with...

**Ex 1**

```java

/*
 * Indicates that at most a single argument will be accepted, its value placed in 'foo'. 
 * More than one argument will be considered an error.
 */
@Parameter(arity = 1)
public String foo;

/*
 * Indicates that at least two arguments will be accepted, their values placed in 'foo'.
 * Fewer than two or more than four arguments will be considered an error.
 */
@Parameter(minArity = 2, arity = 4)
public List<String> foo;

/*
 * Indicates that 0-2 arguments will be accepted, their values placed in 'foo'.
 * More than two arguments will be considered an error.
 */
@Parameter(arity = 2)
public List<String> foo;

```

**Comment by cbeust** [comment]
Sounds reasonable.

Looking at the code, it looks like it's not possible to verify the case where `arity=1` because it's the default, so I can't tell if that value is 1 because the user specified it or because it's the default. So I'll need to make a special case for arity 1, which will be handled by a non-`List` main parameter.

**Comment by rtomsick** [comment]
> Looking at the code, it looks like it's not possible to verify the case where arity=1 because it's the default, so I can't tell if that value is 1 because the user specified it or because it's the default.

Ah.

Didn't notice that.

Shouldn't be an issue then.  I'd then propose the following:

1) Make `arity` default to a sentinel out-of-range value, constified somewhere (`VARIABLE_ARITY` or whatever)

2) Document `arity`'s default behavior as being type-specific (i.e. `List` means variadic, non-collection types mean a single argument is accepted)

3) The existing `List` handling code becomes the special case for when `arity == VARIABLE_ARITY`.  The new behavior (when `!=`) becomes a size check.

---

This seems like it solves all issues in this thread.  It preserves backwards compatibility (where variable arity was assumed), allows for old code to be modified to let JCommander handle arity validation, and provides a simple, no-property form of `@Parameter` that lets people like the OP do single-argument commands easily.

**Comment by cbeust** [comment]
Actually I was wrong, the default for arity is -1 so no issues there.

I implemented the first part.

**Comment by rtomsick** [comment]
Even better. :)

**Comment by cbeust** [comment]
Fixed in 1.72.

**Comment by walles** [comment]
Thanks for fixing this @cbeust!

I just tried this in 1.72 and it works like a charm :)
